version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - internal
      - default  # для доступа Grafana к app (если нужно)
    environment:
      - PROMETHEUS_PUSH_GATEWAY=pushgateway:9091
    restart: unless-stopped
    ports:
      - "8080:8080"


  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - internal
    restart: unless-stopped
    # ports удалены, так как сервис теперь во внутренней сети

  pushgateway:
    image: prom/pushgateway:latest
    networks:
      - internal
    restart: unless-stopped
    # ports удалены, так как сервис теперь во внутренней сети

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    networks:
      - internal  # для доступа к Prometheus и другим сервисам
      - default
    restart: unless-stopped

networks:
  internal:
    internal: true  # сеть доступна только для контейнеров Docker