# yaml-language-server: $schema=https://raw.githubusercontent.com/kubernetes-sigs/kind/main/site/static/schema.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000
        hostPort: 8080
        protocol: TCP
      - containerPort: 30001
        hostPort: 9090
        protocol: TCP
      - containerPort: 30002
        hostPort: 3000
        protocol: TCP
      - containerPort: 30003
        hostPort: 9091
        protocol: TCP